---
resources:
  - name: code
    type: git
    source: 
      url: https://github.com/Shubham-Gupta3197/Concourse-CI
      branch: master

jobs:
  - name: compile
    plan: 
      - get: code
        trigger: true
      - task: clean-compile
        config: 
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: maven
          inputs:
            - name: code
          run: 
            path: mvn
            args: 
              - clean
              - compile
              - -f
              - code/pom.xml  
